---
- name: Download a single file from a public GitHub repo
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/gouldt/playground/main/playground/get_hostname.yml
    validate_certs: false
    dest: /opt/get_hostname.yml
    mode: '0644'
  delegate_to: localhost
